### ISSUE TITLE
Caught exception: TypeError: Object #<an Object> has no method 'forEach' 

### ISSUE THREAD

**Issue by overra** [mape/node-express-boilerplate#1]
connect@0.2.4                            =creationix =tjholowaychuk active installed latest stable remote
connect-assetmanager@0.0.5               =mape active installed latest remote
connect-assetmanager-handlers@0.0.10     =mape active installed latest remote
ejs@0.2.0                                =tjholowaychuk active installed latest stable remote
express@1.0.0rc2                         =tjholowaychuk active installed latest stable remote

node 0.2.1

Caught exception: TypeError: Object #<an Object> has no method 'forEach'
[ 'TypeError: Object #<an Object> has no method \'forEach\''
, '    at /usr/local/lib/node/.npm/connect-assetmanager/0.0.5/package/lib/assetmanager.js:17:12'
, '    at assetManager (/usr/local/lib/node/.npm/connect-assetmanager/0.0.5/package/lib/assetmanager.js:170:7)'
, '    at Object.<anonymous> (/home/adam/git-repos/node-express-boilerplate/server.js:12:14)'
, '    at Module._compile (node.js:462:23)'
, '    at Module._loadScriptSync (node.js:469:10)'
, '    at Module.loadSync (node.js:338:12)'
, '    at Object.runMain (node.js:522:24)'
, '    at Array.<anonymous> (node.js:755:12)'
, '    at EventEmitter._tickCallback (node.js:55:22)'
, '    at node.js:769:9'
]

**Comment by mape** [comment]
What is in the configuration for the asset manager?

**Comment by overra** [comment]
Forgot to mention, this is a fresh installation of everything, including the boilerplate with no changes made.

**Comment by mape** [comment]
Seems like there might have been change to the API in Connect. Will look at a fix.

**Comment by mape** [comment]
Should now be fixed in connect-assetmanager

**Comment by overra** [comment]
Thanks, working now ;)
