### ISSUE TITLE
How to get this working with Express3?

### ISSUE THREAD

**Issue by funkytaco** [mape/node-express-boilerplate#16]
I'm having a problem modifying the code in server.js to use sessions with Express3. Can an updated version be posted or can an example be posted to a wiki page?

I thank you. I've been banging my head on trying to do this and I've been looking at different resources including http://codehenge.net/blog/2012/08/using-socket-io-with-express-3-x/

**Comment by jethrolarson** [comment]
+1

**Comment by funkytaco** [comment]
No pulse on this project. Closing.
