### ISSUE TITLE
Pluggable Template

### ISSUE THREAD

**Issue by JasonGiedymin** [mape/node-express-boilerplate#2]
This is a drive-by issue comment. I think this module is super cool. This module is like a dream for anyone doing any EJS templating. That said, I wish it wasn't hard coded for EJS only filenames. Any plans on making that pluggable (for future xyz, unknown filenames/template engines) and what not?

**Comment by mape** [comment]
With the latest update this should be fixed. Though you would still have to change

```
 app.set('view engine', 'ejs');
```

**Comment by JasonGiedymin** [comment]
Bravo!
