### ISSUE TITLE
A bit more information perhaps?

### ISSUE THREAD

**Issue by nedludd** [mape/node-express-boilerplate#5]
Just a comment from someone just getting started with node and express.

This seems like a great starter kit for an application.  Lots of good stuff in there.

But it might be nice if you explained the structure a bit more in the README.  I looked at the code and started up the server and it's not clear to me what the entry points are.

The server shows the "pongs" from socket.io, on "Online" button, the social networking links (which don't do anything), and two buttons for "Sync browsers" and "Toggle overlay".  But it's not clear what all that means.  You should explain.

Also the nofito and Airbrake stuff.  How would I use it, and why?

Keep up the good work, I'm not criticizing at all, I would just like to see a bit more explanation of how the pieces fit together and how I can make use of it.

Thanks

**Comment by JimPanic** [comment]
+1 - more information, please! :)

**Comment by Celestz** [comment]
I would like to know more information about this bundle as well, since I have used nodeJS for very basic stuff in one of my projects and would like to reap the power this stack has.

**Comment by charlesmeyer** [comment]
+1 
Looks good, a tutorial would be awesome. 
We need a good boilerplate like this to lower the barriers to entry for writing great node.js apps.

**Comment by Zearin** [comment]
+10!!!!

Node and Node-Express have really got my interest.  But I have dealt with Apache for so long that it’s really disorienting to take even the first step in such a different setup.  

Better documentation would make the difference between my using this, and being interested-but-not-ready-to-try-just-yet.

**Comment by nedludd** [comment]
So how about it mape?

**Comment by sntran** [comment]
You could modify some settings in siteConfig.js.

You could also modify server.js to add configurations for airbrake and other plugins.

The view you see when you run the server is in views/index.ejs. Modify it for your own layout.

Remember, this is just a boilerplate. You have to tweak it for your own project.

**Comment by mape** [comment]
The project was meant as a starting point where you remove what you don't need and then fiddle with the rest. 
I sadly don't have the time to write a more in depth README but if anyone is up for the test I'd love a pull request.
